package com.exemple.apigateway.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

class GatewayEventTest {

    @Test
    @DisplayName("Doit créer un GatewayEvent avec ID et timestamp auto-générés")
    void shouldCreateGatewayEventWithAutoGeneratedIdAndTimestamp() {
        // Given
        String eventType = "REQUEST_RECEIVED";
        String userId = "user-123";
        String service = "api-gateway";
        String message = "Test message";

        // When
        GatewayEvent event = new GatewayEvent(eventType, userId, service, message);

        // Then
        assertThat(event.getEventId()).isNotNull();
        assertThat(event.getEventId()).hasSize(36); // UUID format
        assertThat(event.getEventType()).isEqualTo(eventType);
        assertThat(event.getUserId()).isEqualTo(userId);
        assertThat(event.getService()).isEqualTo(service);
        assertThat(event.getMessage()).isEqualTo(message);
        assertThat(event.getTimestamp()).isNotNull();
        assertThat(event.getTimestamp()).isBeforeOrEqualTo(LocalDateTime.now());
    }

    @Test
    @DisplayName("Doit créer un GatewayEvent avec tous les arguments")
    void shouldCreateGatewayEventWithAllArgs() {
        // Given
        String eventId = "event-123";
        String eventType = "REQUEST_COMPLETED";
        String userId = "user-456";
        String service = "api-gateway";
        String message = "Completed";
        LocalDateTime timestamp = LocalDateTime.of(2026, 1, 4, 10, 0, 0);

        // When
        GatewayEvent event = new GatewayEvent(eventId, eventType, userId, service, message, timestamp);

        // Then
        assertThat(event.getEventId()).isEqualTo(eventId);
        assertThat(event.getTimestamp()).isEqualTo(timestamp);
    }
}